arcadexyz/arcade-protocol

- contracts/LoanCore.sol
- contracts/OriginationController.sol
- test/Integration.ts
- test/LoanCore.ts
- test/OriginationController.ts
- test/PartialRepayments.ts
- test/RepaymentController.ts
- test/Rollovers.ts
Update origination to have the OC do the following:
1) Withdraw principal from lender
2) Calculate fees (including the interest fee on rollover, not previously accounted for)
3) Send principal less fees to borrower
4) Send fees to LoanCore
Previously, this was done by LoanCore (minus the last step). Re-doing the ordering in this way allows lenders to make a single approval to OC for both origination and rollover (instead of approving the LC for origination and OC for rollover).
In addition, change the flow of funds in `_initialize` to send out the principal before collecting collateral. In a future PR, we will add a callback function at the TODO marker in order to allow the borrower to execute logic via a callback.
After making changes to the approval flow, fix tests to make sure all are …
> Optimistic Settlement: Change Approval Flow and Flow of Tokens on Origination

- contracts/OriginationController.sol
- contracts/errors/Lending.sol
- contracts/interfaces/IExpressBorrow.sol
- contracts/interfaces/IMigrationBase.sol
- contracts/interfaces/IOriginationController.sol
- contracts/interfaces/v3/IOriginationControllerV3.sol
- contracts/lp-migrations/LP1Migration.sol
- contracts/lp-migrations/LP1MigrationBase.sol
- contracts/lp-migrations/LP1MigrationWithItems.sol
- contracts/test/MockSmartBorrower.sol
- contracts/v2-migration/V2ToV3Rollover.sol
- contracts/v2-migration/V2ToV3RolloverBase.sol
- contracts/v2-migration/V2ToV3RolloverWithItems.sol
- contracts/verifiers/ArcadeItemsVerifier.sol
- contracts/verifiers/ArtBlocksVerifier.sol
- contracts/verifiers/PunksVerifier.sol
- test/Integration.ts
- test/OriginationController.ts
- test/PartialRepayments.ts
- test/RepaymentController.ts
- test/Rollovers.ts
- test/utils/eip712.ts
- test/utils/types.ts
This PR adds on to the previous PR #83 by adding a external call to the borrower is there is `callbackData` present in the `initializeLoan` function call. This call allows the borrower in the loan to execute an arbitrary call with the funds they receive from the optimistic settlement. A `MockSmartBorrower` contract has been added to the `contracts/test` folder to demonstrate what an implementation for this feature looks like. Tests have been added to the `OriginationController.ts` file which use this `MockSmartBorrower` contract.
In addition to the addition of the callback. The loan origination functions have been condensed into two entry points. Now, predicate data can be passed to the `initializeLoan` function instead of calling a specific function when this data is required. The same …
> Feat: Borrower callback, condense origination entry points

- contracts/LoanCore.sol
- test/LoanCore.ts
Since lenders cannot use claim during shutdown, this means that borrowers can choose to not repay their loan, leaving lenders without both principal and collateral.
> fix: Remove shutdown modifier from LoanCore claim fn

- contracts/origination/OriginationControllerMigrate.sol
For migration flows reset the borrower cache immediately after the flash loan is repaid. This way an external call cannot take advantage of the borrower cache after the flash loan is executed.
> [Rene-H-1]: OriginationController Migrate, receiveFlashLoan reentrancy

- contracts/origination/RefinanceController.sol
- test/Refinancing.ts
When validating the new loan terms, restrict the new principal to be <= current loan balance.
Added new test covering this case.
> [Rene-H-2]: RefinanceController._validateRefinance() allows the new principal to be greater than the active balance of the old loan

- contracts/LoanCore.sol
- contracts/errors/Lending.sol
- test/PartialRepayments.ts
Removed NoteReceipt check from `claim()`. The custom error `LC_AwaitingWithdrawal()` was also removed from Lending.sol.
Burning of `lenderNotes` is now a conditional based on if the specific NoteReceipt has a balance or not. This check is added to `_burnLoanNotes()`.
In `redeemNote()` the conditional for burning a lenderNote now checks if the loan has been defaulted in addition to the loan repaid check. This is so that a lender can claim a default before redeeming their `NoteReceipt`.
A local scope block needed to be added to `redeemNote()` in LoanCore due to stack-to-deep compiler errors.
> [Rene-H-3, Rene-M-06]: Borrower can abuse partial repayments to deny Lender from redeeming repaid funds

- contracts/libraries/InterestCalculator.sol
- test/PartialRepayments.ts
Add a conditional check to `getProratedInterestAmount()` seeing if the borrower has made a payment to interest after the loan has ended. If they have, the `interestAmountDue` is set to zero. 
Without this check, Lenders would not be able to claim a defaulted loan since the claim fee calculates the prorated interest amount  and the `timeSinceLastPayment = endTimestamp - lastAccrualTimestamp;` would underflow since `lastAccrualTimestamp > endTimestamp`.
Test case added where borrower repays interest after the loan has ended and the lender is still able to claim the default.
> [Rene-H-4]: Underflow in InterestCalculator.sol allows Borrower to default a loan and deny Lender from claiming collateral

- contracts/origination/OriginationController.sol
In `_validateCounterparties()` remove `!OriginationLibrary.isApprovedForContract(callingCounterparty, sig, sighash)` from the 'caller not participant' check. When this statement is present, an attacker can abuse this to force a user with a `Side.BORROW` signature to become a lender (if they have an open approval to OC) in the following scenario:
- Borrower Bob signs terms for is NFT.
- (Bob has open approval to OC and also has the NFT listed for sale on a marketplace)
- Alice buys the NFT off the marketplace and transfers it to their malicious 'borrower' contract.
- Before Bob can call `cancelNonce()`, Alice calls `initializeLoan()` with lender as Bobs wallet and sig as Bobs 'borrow' signature.
- The checks in `_validateCounterparties()` pass and the loan is started since Bob is the …
> [Rene-H-6]: _validateCounterparties() incorrectly checks if sig belongs to the callingCounterparty

- contracts/origination/OriginationCalculator.sol
- contracts/origination/OriginationControllerMigrate.sol
In `_calculateRolloverAmounts()` logic from V3 was carried over into v4 prorated payments which will cause a borrower to overpay when they are rolling over a loan. This is because the function was using the old principal amount in the `rolloverAmounts()` calculations. It should be the current balance of the loan not the starting principal. This way the `repayAmount` in `rolloverAmounts()` is accurate and the following conditionals will properly be executed. Specifically `borrowerOwedForNewLoan > repayAmount`.
This same issue is also present in the refinancing flow since it also uses `_calculateRolloverAmounts()`.
A @dev note has been added to the `_calculateV3MigrationAmounts()` explaining why this function still uses the old loans principal and not the balance since V3 has no concept of …
> [Rene-H-7]: OriginationCalculator._calculateRolloverAmounts() doesn't account for partially repaid loans

- contracts/LoanCore.sol
- contracts/origination/OriginationCalculator.sol
- contracts/origination/OriginationConfiguration.sol
- contracts/origination/OriginationControllerMigrate.sol
- contracts/origination/RefinanceController.sol
Rene-I-01: Use a constant for input array length checks in OriginationConfiguration.sol.
Rene-I-02: Fix comment errors for `_allowedCollateral` in OriginationConfiguration natspec, update the natspec for the `LoanCore.shutdown()` to say defaults can be claimed when shutdown, update natspec for `_validateV3Migration()` to specify v3/v4 not v2/v3.
Rene-I-03: Remove `LoanCore._unpause()` it is unnecessary.
Rene-I-04: Simplify 
`uint256 aprMinimumScaled = oldLoanData.terms.interestRate * Constants.BASIS_POINTS_DENOMINATOR - (oldLoanData.terms.interestRate * MINIMUM_INTEREST_CHANGE);`
to 
`uint256 aprMinimumScaled = oldLoanData.terms.interestRate * (Constants.BASIS_POINTS_DENOMINATOR - MINIMUM_INTEREST_CHANGE);`
Additional cleanup in LoanCore, OriginationController, and …
> [Rene-I-01, Rene-I-02, Rene-I-03, Rene-I-04]: Information fixes and code cleanup

- contracts/RepaymentController.sol
- contracts/errors/Lending.sol
- test/Integration.ts
- test/RepaymentController.ts
Rene-I-05: Remove `if (data.state == LoanLibrary.LoanState.DUMMY_DO_NOT_USE) revert RC_CannotDereference(loanId);` from `RepaymentController.sol._prepareRepay()` since the `!= LoanLibrary.LoanState.Active` covers the same condition.
Rene-I-08: Along the same logic as Rene-I-05, replace `if (data.state == LoanLibrary.LoanState.DUMMY_DO_NOT_USE) revert RC_CannotDereference(loanId);` with `if (data.state != LoanLibrary.LoanState.Active) revert RC_InvalidState(loanId);` to be consistent with the other LoanState validations.
The Lending.sol error `RC_CannotDereference()` has been removed since it is no longer needed. Test using this custom error have been updated to check that the revert is `RC_InvalidState()` instead.
> [Rene-I-05, Rene-I-08]: Consistent LoanLibrary.LoanState validations in RepaymentController.sol

- contracts/RepaymentController.sol
Since there is a check for `if (amount < interestAmount) revert RC_InvalidRepayment(amount, interestAmount);` in `RepaymentController._prepayRepay()` we can make `paymentToPrincipal = amount - interestAmount;` unchecked math since there is no possibility to underflow.
> [Rene-I-06]: paymentToPrincipal calculation can be unchecked in _prepayRepay()

- contracts/libraries/OriginationLibrary.sol
Decode the staticcall to `isValidSignature()` as `bytes32` not `bytes4` similar to how OpenZeppelin does it in their [signature checker](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v5.0/contracts/utils/cryptography/SignatureChecker.sol#L44-L46) contract. This allows an ERC1271 implementer to return the magic value with any amount of padding. With this change they could return the `IERC1271.isValidSignature.selector` as `bytes5`, `bytes16`, ... `bytes32` and the check will still pass.
> [Rene-I-09]: OriginationLibrary.isApprovedForContract() should decode result as bytes32 to avoid unexpected reverts in future use

- contracts/LoanCore.sol
Add the `whenNotPaused()` and `nonReentrant()` modifiers to `setAffiliateSplits()` in LoanCore. This way the function cannot be called by the `AFFILIATE_MANAGER_ROLE` after LoanCore shutdown and the function will be consistent with the other 'whenNotPaused' functions like `startLoan()`, `rollover()`, `canCallOn()`, and `consumeNonce()`.
> [Rene-I-10]: setAffiliateSplits() lacks whenNotPaused and nonReentrant modifiers

- contracts/LoanCore.sol
- contracts/libraries/InterestCalculator.sol
- contracts/origination/OriginationControllerMigrate.sol
Rene-I-11: modify conditional in `_migrate()` to check if `amounts.leftoverPrincipal > 0` not `amounts.amountFromLender > 0` when distributing the `leftoverPrincipal`
Rene-I-12: Add @dev comment to `getProratedInterestAmount()` calculation explain rounding down scenarios that relate to payable currencies with low number of decimals.
Rene-I-13: `LoanCore.claim()` to update `loans[loanId].balance` and `loans[loanId].lastAccrualTimestamp` when loans are defaulted.
> [Rene-I-11, Rene-I-12, Rene-I-13]: Information fixes

- contracts/LoanCore.sol
- contracts/interfaces/ILoanCore.sol
- contracts/origination/OriginationController.sol
- contracts/origination/OriginationControllerMigrate.sol
- test/LoanCore.ts
- test/utils/loans.ts
In `OriginationControllerMigrate._initializeMigrationLoan()`, `startLoan()` in LoanCore is not being called properly. It differs from how `OriginationController.initializeLoan()` calls startLoan() such that the the `amountFromLender` and `amountToBorrower` do not stand for the same things. This is because the migration flow uses `OriginationCalculator.rolloverAmounts()` where those variables stand for different things as opposed to what they stand for in `OriginationController.initializeLoan()`. The downstream affect of this is that `LoanCore.startLoan()` does not calculate the fees correctly causing `feesEarned` to end up becoming a largely inflated value.
To remedy this, the sum of `borrowerFee + lenderFee` is used as the `amountFromLender` value and `amountToBorrower` is `0`. This mean …
> [Rene-H-5]: Incorrect fee calculation when migrating V3 loans in OriginationControllerMigrate.migrateV3Loan()

- contracts/origination/OriginationControllerMigrate.sol
Use the explicit v3 repayment amount for the the flash loan amount. Previously the amount was derived from the RolloverAmounts, but when fees are involved, this will leave a `> 0` approval towards V3 LoanCore and since we are using safe approvals, subsequent approvals will revert since the current approval is non-zero.
> [Rene-M-01]: Permanent DOS of OriginationControllerMigrate.migrateV3Loan() after the first migration

- contracts/LoanCore.sol
- test/LoanCore.ts
This PR fixes cases where a signature can be used infinitely since, `_nonceUses + 1 == maxUses` will never be true in `_useNonce()`. To fix this we add a conditional saying when `maxUses <= _nonceUses` revert.
This can occur when a user  signs a signature with `maxUses = 0` OR a user signs a signature with the same nonce and the new signature's `maxUses` value is less than the number of times that nonce has already been used.
> [Rene-M-02]: In some cases a signature's nonce maxUses can be violated

- contracts/FeeController.sol
- contracts/LoanCore.sol
- contracts/RepaymentController.sol
- contracts/interfaces/ILoanCore.sol
- contracts/libraries/FeeLookups.sol
- test/FeeController.ts
- test/Integration.ts
- test/LoanCore.ts
- test/RepaymentController.ts
Since the borrower has the option to use force repayments, this will always incur a `LENDER_REDEEM_FEE` on the lender's NoteReceipt balance which is a form of grieving.
In addition to this change, the lenders address is now passed into `LoanCore.redeemNote()`. We are already checking that the caller is the lender in `RepaymentController.redeemNote()` so there is no need to get the lender address again in `LoanCore.redeemNote()`.
Lastly, I replaced `_transferIfNonzero(IERC20(token), to, amount);` with `IERC20(token).safeTransfer(to, amount);` since we are already checking that amount is non-zero.
> [Rene-M-03]: Remove FL_08 from FeeController

- README.md
- contracts/FeeController.sol
- contracts/interfaces/IFeeController.sol
- contracts/libraries/FeeLookups.sol
- contracts/origination/OriginationCalculator.sol
- contracts/origination/OriginationController.sol
- contracts/origination/OriginationControllerMigrate.sol
- test/FeeController.ts
- test/Integration.ts
- test/Refinancing.ts
- test/RepaymentController.ts
- test/Rollovers.ts
- test/utils/constants.ts
This PR includes a refactor of the rollover fees. `FL-03` and `FL_04` rollover fees have been removed entirely.
We have chosen to enforce the FL_01 and FL_02 origination fees everywhere a new loan is started. This is starting a loan, rollovers, migrations, and refinancing. 
This solves three issues: 1). For Rene-M-05 now there are no "old" vs "new" fees, everything is origination and goes to the new affiliate. 2). There is a known [gotcha](https://github.com/arcadexyz/arcade-protocol?tab=readme-ov-file#loan-origination-fees-are-upper-bounded-by-rollover-fees) in V3 where if fees were ever set such that rollover fees were lower than origination fees, counterparties become incentivized to circumvent fees. 3). for Rene-M-04, it was suggested to add the `principalFee` to the rolloverAmounts …
> [Rene-M-04, Rene-M-05]: Removing rollover fees

- contracts/interfaces/IOriginationController.sol
- contracts/libraries/OriginationLibrary.sol
- contracts/origination/OriginationController.sol
- contracts/origination/OriginationControllerMigrate.sol
- test/OriginationController.ts
- test/utils/eip712.ts
- test/utils/types.ts
Add the signingCounterparty to `_TOKEN_ID_TYPEHASH` and`_ITEMS_TYPEHASH`. 
This led to a refactor of the sigHash itself, specifically the SigProperties. This part is now encoded similar to the ItemsPredicates. This change was due to stack-too-deep and needing to simplify the number of inputs to the abi encoding in `recoverItemsSignature`.
> [Rene-M-7]: Missing signingCounterparty in loanHash can lead to the signature being used with the wrong address

- contracts/origination/OriginationCalculator.sol
- test/Refinancing.ts
The `interestFee` should only be charged to the new lender on rollovers when the `oldLender == newLender`. In the case where the lenders are different. The interestFees is subtracted from the amount owed to the old lender.
> [Rene-M-08]: New lenders are unfairly charged for interestFee when rolling over an loan

- contracts/RepaymentController.sol
When a lender claims a default they are required to pay a 'claim fee' based on the total value of the loan. Prior to this fix, if there was a partial repayment on a defaulted loan, the interest amount paid in the partial repayment was not factored into the total value of the loan and resulted in the protocol loosing out on fees when the fee was calculated in `RepaymentController.claim()`.
> [Rene-M-12]: totalOwed does not account for partial repayments

- contracts/origination/OriginationCalculator.sol
- contracts/origination/OriginationController.sol
- test/Rollovers.ts
In scenarios where `lender == oldLender` and `borrowerOwedForNewLoan < repayAmount < amountFromLender` the protocol does not end up collecting the lender and interest fees.
This PR makes a change to the OriginationCalculator and OriginationController._rollover() to account for these fees similar to how `OriginationControllerMigrate._migrate()` accounts for the `leftoverPrincipal`.
Test added to `Rollovers.ts` to show a scenario where this is applicable.
> [Rene-M-13]: lenderFee and interestFee may not be collected from new lenders on rollover

- contracts/errors/Lending.sol
- contracts/origination/OriginationControllerMigrate.sol
Instead of having separate loan terms checks just for migration flows, utilize `OriginationConfiguration.validateLoanTerms()`. This ensures a comprehensive check of all the new loan terms similar to any of the origination flows. With this change I removed all the dedicated OCM errors in Lending.sol that were no longer needed.
> [Rene-L-1]: Missing isAllowedCollateral() inside OriginationControllerMigrate_validateV3Migration()

- contracts/errors/Lending.sol
- contracts/origination/RefinanceController.sol
- test/Refinancing.ts
Rene-L-2: Added `newTerms.durationSecs < Constants.MIN_LOAN_DURATION` to the conditional checking the loan duration constraints.
Rene-L-3: Added check ensuring the new principal amount is not lower than the allowable minimum for the specific payable currency.
> [Rene-L-2, Rene-L-3]: Missing MIN_LOAN_DURATION and minimum principal checks in RefinanceController._validateRefinance()

- contracts/LoanCore.sol
When a loan is rolled over, update the `data.lastAccrualTimestamp` to the current block.timestamp. This way in future when someone wants to calculate the effective APR the LoanData will be accurate. This state update already happens in `LoanCore._handleRepay()` so does not need to be added there.
> [Rene-L-5]: Lack of state update in LoanCore.rollover() can lead to inflated effective APR

- contracts/interfaces/IOriginationController.sol
- contracts/libraries/OriginationLibrary.sol
- contracts/origination/OriginationController.sol
- contracts/origination/OriginationControllerMigrate.sol
- test/OriginationController.ts
- test/utils/eip712.ts
- test/utils/types.ts
When starting a loan, a callee can assign `callbackData` to the` borrowerData` to execute an operation once the loan is initialized. Technically the lender can pass any data they want here to be executed on the borrower even if the borrower is not expecting it. In order to make this a more explicit action that the borrower can be aware of, the borrower `callbackData` is now included in the loan signature. This way the borrower will always be aware of it before using the a lenders signature to start a loan.
This change required some refactoring of the signature recovery flow to break down the encoding into smaller chunks to avoid stack-to-deep errors.  When looking at the type hashes in OriginationLibrary.sol you can see that they have been broken down into chunks that are similar to their …
> [Rene-M-09]: Include borrower callback data in the loan signatures

- scripts/deploy/deploy.ts
- scripts/deploy/record-deployment.ts
- scripts/deploy/setup-roles.ts
- scripts/deploy/whitelisting.ts
- scripts/utils/constants.ts
- scripts/utils/deploy.ts
- scripts/v3-migration/v3-migration-diff-lender.ts
- scripts/v3-migration/v3-migration-same-lender.ts
Add OriginationConfiguration contract to the deploy script and update the `whitelisting.ts` script to use this contract instead of the OriginationController. Also update helper files like `record-deployment.ts` to capture the OriginationConfiguration deployment.
> Fix: deployment scripts, add OriginationConfiguration deployment

- contracts/errors/Lending.sol
- contracts/origination/RefinanceController.sol
- test/Refinancing.ts
A check has been added to `RefinanceController:: _validateRefinance()` that validates the loan to be refinanced has not yet reached its expiration. This check is to be added to protect the original lender from being frontrun by a refinance tx while they try to claim the defaulted collateral.
A test has been added showing once the loan duration has been reached, refinancing no longer works. Additionally it was found in most of the other 'Refinancing Constraints' tests that the approval from the new lender for refinancing was being made to the wrong contract and breaking the testing pattern of only having one 'variable' change per test.
> [Cantina-Med-4]: Cannot refinance once the loan duration has been reached

- contracts/RepaymentController.sol
- contracts/errors/Lending.sol
- test/PartialRepayments.ts
- test/RepaymentController.ts
This PR modifies the repayment flow to check if the timestamp the repayment is being made at is equal to or past the loans due date. If it is, partial payments are not accepted only full repayments. This change is necessary to protect borrowers from a lender who will wait for a partial repayment after the loan duration has ended to claim the collateral. Meaning the borrower looses the partial repayment amount and defaults on the loan.
Various tests have been updates to conform to this new repayment logic.
>  [Cantina-Low-11]: Only full repayments after loan duration has been passed

- contracts/errors/Lending.sol
- contracts/origination/OriginationControllerMigrate.sol
For v3 migrations add a check that the newLender is not the v3 borrower. `msg.sender` is validated as the borrower (holder of the borrower note) in `MigrateV3Loan:: _validateV3Migration()` so it is safe to compare the `msg.sender` to the newLender address.
This check is present in the loan origination flow `OriginationController:: _validateCounterparties()`:
```
if (caller == signer || caller == signingCounterparty) revert OC_ApprovedOwnLoan(caller);
```
Since migrations are another way to originate a v4 loan, the same the equivalent check should be present.
This error can be triggered in the mainnet fork migration scripts by modifying them to send the v3 borrower note to the newLender and having the newLender initiate the call to the migration function.
> [Cantina-Low-12]: add new lender validation to v3 migrations 

- contracts/interfaces/IExpressBorrow.sol
- contracts/interfaces/IOriginationController.sol
- contracts/libraries/OriginationLibrary.sol
- contracts/origination/OriginationController.sol
- contracts/origination/OriginationControllerMigrate.sol
- contracts/test/MockSmartBorrower.sol
- test/OriginationController.ts
- test/utils/eip712.ts
- test/utils/types.ts
This reverts PR #118 where the borrower callback data was added to be in the loan signatures. This was not the optimal solution as is made it so all lender signatures would need to know specific borrower callback data at the time of signing, which is not realistic and adds a lot of friction to collection wide offer signatures. 
The original intention of PR 118 was to make it so the lender could not execute arbitrary callback data on the borrower which the borrower had no control over what that executed data would be. With this fix, this same issue is addressed another way. Instead of including the callback data in the signature, the conditional to execute the callback checks if the `neededSide` is LEND this way we know the borrower or a borrower approved account is making the loan …
> Remove borrower callback from loan signatures

- scripts/deploy/deploy.ts
Add await statements to the `OriginationHelpers` and `OriginationLibrary` deployments in `deploy.ts` script. Without these await statements, hardhat gets confused when deploying the `OriginationControllerMigrate` contract since there is a nonce for a previous deployment still being executed and it tries to use the same nonce for the `OriginationControllerMigrate` deployment.
> Deploy script updates for V4 (part 2)
